
spring:
  zipkin:
    base-url: http://localhost:9411/
#  mvc:
#      pathmatch:
#            matching-strategy: ant-path-matcher
springdoc:
  api-docs:
    path: /shipmentApi
        
logging:
  level:
    '[org.springframework.web]': error
    '[com.exam.shipement]': debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    dateformat: 
    
  file: 
    path: C:\Users\vkarna654\Documents\workspace-spring-tool-suite-4-4.13.1.RELEASE\shipmentlogs.log